### ISSUE TITLE
Build for mesos v0.27.0

### ISSUE THREAD

**Issue by pradeepchhetri** [emccode/mesos-module-dvdi#70] opened 2016-02-02 14:34 UTC
It will be nice if we can add support for building dvdi module with mesos v0.27.0.

**Comment by davidvonthenen** [comment] 2016-02-02 17:05
Yep, we are working on it. We are waiting for the official 27 binaries for qualification.

Already have an issue open for 0.27.0, you can find it here: https://github.com/emccode/mesos-module-dvdi/issues/43

**Comment by cantbewong** [comment] 2016-02-08 17:45
closing as a duplicate of issue 43

**Closed as completed** 2016-02-08 17:45 UTC
